install.packages("Seurat")
install.packages("ggplot2")
library(ggplot2)
library(Seurat)
library(dplyr)
library(Matrix)
library(sctransform)
setwd("/mnt")
p1 <- readRDS("p1t1_v1.rds")
p2 <- readRDS("p1t2_v1.rds")
p3 <- readRDS("p1t3_v1.rds")
p4 <- readRDS("p1t4_v1.rds")
p5 <- readRDS("p2t1_v1.rds")
p6 <- readRDS("p2t2_v1.rds")
p7 <- readRDS("p3t1_v1.rds")
p8 <- readRDS("p3t2_v1.rds")
p9 <- readRDS("p3t3_v1.rds")
p10 <- readRDS("p4t1_v1.rds")
p11 <- readRDS("p4t2_v1.rds")
p12 <- readRDS("p4t3_v1.rds")
p13 <- readRDS("p5t1_v1.rds")
p14 <- readRDS("p5t2_v1.rds")
p15 <- readRDS("p6t1_v1.rds")
p16 <- readRDS("p6t2_v1.rds")
p17 <- readRDS("p7t1_v1.rds")
p18 <- readRDS("p7t2_v1.rds")
tumor_merged <- merge(p1, y = c(p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18), add.cell.ids = c("p1t1", "p1t2", "p1t3", "p1t4", "p2t1", "p2t2", "p3t1", "p3t2", "p3t3", "p4t1", "p4t2", "p4t3", "p5t1", "p5t2", "p6t1", "p6t2", "p7t1", "p7t2"), project = "tumor_merged")
tumor_merged
tumor_merged[[]]
unique(sapply(X = strsplit(colnames(tumor_merged), split = "_"), FUN = "[", 1))
unique(sapply(X = strsplit(rownames(tumor_merged), split = "_"), FUN = "[", 1))
table(tumor_merged$orig.ident)
tumor_merged.list <- SplitObject(object = tumor_merged, split.by = "orig.ident")
p1.list <- lapply(X = tumor_merged.list, FUN = function(x) {
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})
tumor_merged.features <- SelectIntegrationFeatures(object.list = p1.list, nfeatures = 3000)
tumor_merged.anchors <- FindIntegrationAnchors(object.list = p1.list, anchor.features = tumor_merged.features)
tumor.combined <- IntegrateData(anchorset = tumor_merged.anchors)
DefaultAssay(tumor.combined) <- "integrated"
tumor.combined_scaledata <- ScaleData(tumor.combined, verbose = FALSE)
tumor.combined_RunPCA <- RunPCA(tumor.combined_scaledata, npcs = 30, verbose = FALSE)
tumor.combined_RunTSNE <- RunTSNE(tumor.combined_RunPCA, reduction = "pca", dims = 1:30)
tumor.combined_findneighbors <- FindNeighbors(tumor.combined_RunTSNE, reduction = "pca", dims = 1:30)
tumor.combined_findclusters <- FindClusters(tumor.combined_findneighbors, resolution = 0.5)
p1_plot <- DimPlot(tumor.combined_findclusters, reduction = "tsne", group.by = "orig.ident")
p2_plot <- DimPlot(tumor.combined_findclusters, reduction = "tsne", label = TRUE, repel = TRUE)
p1_plot+p2_plot
tumor.combined_markers <- FindAllMarkers(object = tumor.combined_findclusters,only.pos = TRUE,
                                         logfc.threshold = 0.25)
write.csv(tumor.combined_markers, "tumor_markers_final.csv")
FeaturePlot(tumor.combined_findclusters, features = c("MS4A1", "CD19", "CD79A", "ITGAX"), cols = c("grey", "yellow", "red"), reduction = "umap")
VlnPlot(tumor.combined_findclusters, features = c("MS4A1", "CD19", "TNFRSF13B", "MZB1", "IGHM", "JCHAIN", "PRDM1", "XBP1", "CD79A", "FCRL4"))
current.cluster.ids=c(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22)
new.cluster.ids = c("0", "1", "B cells", "3", "4", "5", "6", "7", "8", "B cells", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22")
names(x = new.cluster.ids) <- levels(x = tumor.combined_findclusters)
tumor.combined_findclusters <- RenameIdents(object = tumor.combined_findclusters, new.cluster.ids)
DimPlot(object = tumor.combined_findclusters, reduction = "tsne", label = TRUE, pt.size = 0.5)
#subset
B_plasma <- subset(tumor.combined_findclusters, idents = c("B cells"))
DimPlot(B_plasma, reduction = "tsne", label = TRUE)
B_plasma_scaledata <- ScaleData(B_plasma, verbose = FALSE)
B_plasma_RunPCA <- RunPCA(B_plasma_scaledata, npcs = 30, verbose = FALSE)
B_plasma_RunTSNE <- RunTSNE(B_plasma_RunPCA, reduction = "pca", dims = 1:30)
B_plasma_findneighbors <- FindNeighbors(B_plasma_RunTSNE, reduction = "pca", dims = 1:30)
B_plasma_findclusters <- FindClusters(B_plasma_findneighbors, resolution = 0.5)
p1_plot <- DimPlot(B_plasma_findclusters, reduction = "tsne", group.by = "orig.ident")
p2_plot <- DimPlot(B_plasma_findclusters, reduction = "tsne", label = TRUE, repel = TRUE)
p1_plot+p2_plot
B_plasma_markers <- FindAllMarkers(object = B_plasma_findclusters,only.pos = TRUE,
                                   logfc.threshold = 0.25)
write.csv(B_plasma_markers, "B.markers.csv")
#subset further, take cluster3 out
current.cluster.ids=c(0,1,2,3,4,5,6)
new.cluster.ids = c("B", "B", "B", "3", "B", "5", "B")
names(x = new.cluster.ids) <- levels(x = B_plasma_findclusters)
B_plasma_findclusters <- RenameIdents(object = B_plasma_findclusters, new.cluster.ids)
DimPlot(object = B_plasma_findclusters, reduction = "tsne", label = TRUE, pt.size = 0.5)
B <- subset(B_plasma_findclusters, idents = c("B"))
DimPlot(B, reduction = "tsne", label = TRUE)
B_scaledata <- ScaleData(B, verbose = FALSE)
B_RunPCA <- RunPCA(B_scaledata, npcs = 30, verbose = FALSE)
B_RunTSNE <- RunTSNE(B_RunPCA, reduction = "pca", dims = 1:30)
B_findneighbors <- FindNeighbors(B_RunTSNE, reduction = "pca", dims = 1:30)
B_findclusters <- FindClusters(B_findneighbors, resolution = 0.5)
p1_plot <- DimPlot(B_findclusters, reduction = "tsne", group.by = "orig.ident")
p1_plot+p2_plot
B_markers <- FindAllMarkers(object = B_findclusters,only.pos = TRUE,
                                   logfc.threshold = 0.01)
write.csv(B_markers, "B_only_markers.csv")