install.packages("Seurat")
install.packages("ggplot2")
library(ggplot2)
library(Seurat)
library(dplyr)
library(Matrix)
library(sctransform)
setwd("/mnt")
LC <- Read10X(data.dir = "/mnt/LC_counts/")
LC_v1 <- CreateSeuratObject(counts = LC, min.cells = 3, min.features  = 200)
mito.genes <- grep(pattern = "^MT-", x = rownames(LC_v1@assays[["RNA"]]), value = TRUE)
percent.mito <- Matrix::colSums(LC_v1@assays[["RNA"]][mito.genes, ])/Matrix::colSums(LC_v1@assays[["RNA"]])
LC_v1 <- AddMetaData(object = LC_v1, metadata = percent.mito, col.name = "percent.mito")
LC_v1$percent.mito <- percent.mito
VlnPlot(object = LC_v1, features = c("nFeature_RNA", "nCount_RNA", "percent.mito"), ncol = 3)
par(mfrow = c(1, 2))
FeatureScatter(object = LC_v1, feature1 = "nCount_RNA", feature2 = "percent.mito")
FeatureScatter(object = LC_v1, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
LC_v1 <- subset(x = LC_v1, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mito >  -Inf & percent.mito < 0.05 )
LC_v1 <- NormalizeData(object = LC_v1, normalization.method = "LogNormalize", scale.factor = 10000)
LC_v1 <- FindVariableFeatures(object = LC_v1, mean.function = ExpMean, dispersion.function = LogVMR, x.low.cutoff = 0.0125, x.high.cutoff = 3, y.cutoff = 0.5, nfeatures = 2000)
head(x = HVFInfo(object = LC_v1))
LC_v1_scaledata <- ScaleData(object = LC_v1, vars.to.regress = c("nCounts_RNA", "percent.mito"))
LC_v1_RunPCA <- RunPCA(object = LC_v1_scaledata,  npcs = 30, verbose = FALSE)
LC_v1_RunUMAP <- RunUMAP(object = LC_v1_RunPCA, reduction = "pca", dims = 1:20)
LC_v1_findneighbors <- FindNeighbors(LC_v1_RunUMAP, reduction = "pca", dims = 1:20)
LC_v1_findclusters <- FindClusters(LC_v1_findneighbors, resolution = 0.5)
DimPlot(LC_v1_findclusters, reduction = "umap")
FeaturePlot(LC_v1_findclusters, features = c("MS4A1", "CD19", "CD79A", "ITGAX"), cols = c("grey", "yellow", "red"), reduction = "umap")
VlnPlot(LC_v1_findclusters, features = c("MS4A1", "CD19", "CD79A", "ITGAX", "FCRL4", "MZB1", "CD14"))
saveRDS(LC_v1, "LC_v1.rds")
#Find markers
LC_v1.markers <- FindAllMarkers(object = LC_v1, only.pos = TRUE, min.pct = 0.25, thresh.use = 0.25)
write.csv(LC_v1.markers, "Lambrechts_allmarkers.csv")
#Identifying cluster 3 as B cells and cluster 9 as plasma cells
current.cluster.ids=c(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23)
new.cluster.ids = c("0", "B cells", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23")
names(x = new.cluster.ids) <- levels(x = LC_v1_findclusters)
LC_v1_findclusters <- RenameIdents(object = LC_v1_findclusters, new.cluster.ids)
DimPlot(object = LC_v1_findclusters, reduction = "umap", label = TRUE, pt.size = 0.5)
#Subclustering cluster3 B cells only
B <- subset(LC_v1_findclusters, idents = c("B cells"))
DimPlot(B, reduction = "umap", label = TRUE)
B_scaledata <- ScaleData(B, verbose = FALSE)
B_RunPCA <- RunPCA(B_scaledata, npcs = 30, verbose = FALSE)
B_RunUMAP <- RunUMAP(B_RunPCA, reduction = "pca", dims = 1:20)
B_findneighbors <- FindNeighbors(B_RunUMAP, reduction = "pca", dims = 1:20)
B_findclusters <- FindClusters(B_findneighbors, resolution = 0.5)
DimPlot(B_findclusters, reduction = "umap",label = TRUE, pt.size = 1.0)
VlnPlot(B_findclusters, features = c("MS4A1", "CD19", "CD79A", "ITGAX", "FCRL4", "IGHD", "CD27", "IGHM", "GPR183", "FCRL5", "CD52", "TBX21"))
FeaturePlot(B_findclusters, features = c("MS4A1", "CD19", "CD79A", "ITGAX", "FCRL4", "IGHD", "CD27", "IGHM", "GPR183", "FCRL5", "CD52", "TBX21"), cols = c("grey", "yellow", "red"), reduction = "umap")
B_markers <- FindAllMarkers(object = B_findclusters,only.pos = TRUE,
                            logfc.threshold = 0.05)
write.csv(B_markers, "B_markers.csv")
